Document: algolint
Title: Debian algolint Manual
Author: <insert document author here>
Abstract: This manual describes what algolint is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/algolint/algolint.sgml.gz

Format: postscript
Files: /usr/share/doc/algolint/algolint.ps.gz

Format: text
Files: /usr/share/doc/algolint/algolint.text.gz

Format: HTML
Index: /usr/share/doc/algolint/html/index.html
Files: /usr/share/doc/algolint/html/*.html
